# Generated by Django 5.2.1 on 2025-05-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.level'),
        ),
    ]
