# Generated by Django 5.2.1 on 2025-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='answer_options',
            field=models.JSONField(default=list),
        ),
    ]
