# Generated by Django 5.2.1 on 2025-05-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='task',
            name='option4',
        ),
        migrations.AddField(
            model_name='task',
            name='answer_options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
