# Generated by Django 5.2.1 on 2025-05-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_option1_remove_task_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_options',
            field=models.TextField(blank=True, help_text="Введите варианты ответа, разделяя их запятыми (например: 'Опция A, Опция B, Опция C').", null=True),
        ),
    ]
